[program:enterlms-queue]
command=/usr/bin/php __APP_DIR__/artisan queue:work database --sleep=1 --tries=3 --timeout=120 --max-time=3600
directory=__APP_DIR__
user=www-data
numprocs=1
autostart=true
autorestart=true
stopwaitsecs=25
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/var/log/enterlms/queue.log
stdout_logfile_maxbytes=10MB

[program:enterlms-scheduler]
command=/usr/bin/php __APP_DIR__/artisan schedule:work
directory=__APP_DIR__
user=www-data
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/var/log/enterlms/scheduler.log
stdout_logfile_maxbytes=10MB
